import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Header from "~/components/Header";
import Image from "next/image";
import ContentList from "~/components/ContentList";

const Home: NextPage = () => {
  const { data: contents } = api.content.getAllContents.useQuery();
  return (
    <>
      <Head>
        <title>19-didemevran</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex w-full justify-center">
        <Image
          alt="Logo"
          width={1000}
          height={400}
          layout="responsive"
          src="/../public/mainpicture.png"
        />
      </div>
      <div className="flex justify-center my-10 gap-10">
        <ContentList contents={contents} />
      </div>
    </>
  );
};

export default Home;
